[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](
https://colab.research.google.com/github/CMU-IDeeL/CMU-IDeeL.github.io/blob/master/F25/document/Recitation_0_Series/0.4/0_4_Pytorch.ipynb)

# **Exercise for Introduction to PyTorch Fundamentals**

### IMPORTANT NOTE: To avoid version mismatch errors with Autolab, please ensure you are using commands that are from the following versions of [*NumPy*](https://numpy.org/) and [*Torch*](https://pytorch.org/) :    
`numpy==1.16.4`  
`torch==1.2.0`  
if your installation fails, make sure you are using a virtual environment with `python v3.7.13` installed
  
For example,
Consider using `torch.mul(x, y)` instead of `torch.multiply(x, y)`.

Why? `torch.mul(x, y)` is available in version `torch==1.2.0`, whereas `torch.multiply(x, y)` is not. Using `torch==1.2.0` will help us avoid unpleasant issues with AutoLab's default versioning.

---




> PyTorch is an open source deep learning platform that provides a seamless path from research prototyping to production deployment.
> - *Hybrid Front-End:* A new hybrid front-end seamlessly transitions between eager mode and graph mode to provide both flexibility and speed.
> - *Distributed Training:* Scalable distributed training and performance optimization in research and production is enabled by the torch.distributed backend.
> - *Python-First:* Deep integration into Python allows popular libraries and packages to be used for easily writing neural network layers in Python.
> - *Tools & Libraries:* A rich ecosystem of tools and libraries extends PyTorch and supports development in computer vision, NLP and more.
>
> —*[About PyTorch](https://pytorch.org/)*

One consideration as to why we are using PyTorch is most succinctly summerized by Andrej Karpathy, Former Director of Artificial Intelligence and Autopilot Vision at Tesla. The technical summary can be found [here](https://twitter.com/karpathy/status/868178954032513024?lang=en).

You also refer a brief summary on PyTorch by Nvidia [here](https://www.nvidia.com/en-us/glossary/data-science/pytorch/).

For this notebook you can refer to the documentation provided by PyTorch [here](https://pytorch.org/docs/stable/nn.html).

In [1]:
import numpy as np
print(np.__version__)
import os
import time
import torch
print(torch.__version__)

# Expected outputs for local (used for HW part1s):
# 1.16.4
# 1.2.0

# Expected outputs for colab (used for HW part2s):
# 1.23.5
# 2.1.0+cu121

2.0.2
2.8.0+cu126


### **1. Interconversion**

#### 1.1 Converting from NumPy to PyTorch Tensor

*   List item
*   List item


In this task, you will implement a conversion function from arrays to tensors.

The function should take a numpy ndarray and convert it to a PyTorch tensor.

*Function torch.tensor is one of the simple ways to implement it but please do not use it this time. The PyTorch environment installed on Autolab is not an up-to-date version and does not support this function.*

**Your Task**: Implement the function `numpy2tensor`.

In [2]:
def numpy2tensor(x):
    """
    Creates a torch.Tensor from a numpy.ndarray.

    Parameters:
    x (numpy.ndarray): 1-dimensional numpy array.

    Returns:
    torch.Tensor: 1-dimensional torch tensor.
    """

    return  torch.from_numpy(x) #NotImplemented   # TODO

##### Test Example:

In [3]:
X = np.random.randint(-1000, 1000, size=3000)

print(type(numpy2tensor(X)))

<class 'torch.Tensor'>


In [4]:
t = numpy2tensor(X)
X[0] += 1
print(t[0].item(), X[0])  # should match


996 996


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt> &lt;class &#39;torch.Tensor&#39;&gt; </tt></td>
    </tr>
</table>

#### 1.2 Converting from PyTorch Tensor to NumPy

In this task, you will implement a conversion function from tensors to arrays.

The function should take a PyTorch tensor and convert it to a numpy ndarray.

**Your Task**: Implement the function `tensor2numpy`.

In [5]:
def tensor2numpy(x):
    """
    Creates a numpy.ndarray from a torch.Tensor.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    numpy.ndarray: 1-dimensional numpy array.
    """

    return x.numpy() # TODO

##### Test Example:

In [6]:
X = np.random.randint(-1000, 1000, size=3000)
X = torch.from_numpy(X)

print(type(tensor2numpy(X)))

<class 'numpy.ndarray'>


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt> &lt;class &#39;numpy.ndarray&#39;&gt; </tt></td>
    </tr>
</table>

### **2. Vectorization**

Lists are a foundational data structure in Python, allowing us to create simple and complex algorithms to solve problems. However, in mathematics and particularly in linear algebra, we work with vectors and matrices to model problems and create statistical solutions. Through these exercises, we will begin introducing you to how to think more mathematically through the use of PyTorch by starting with a process known as vectorization.

Index chasing is a very valuable skill, and certainly one you will need in this course, but mathematical problems often have simpler and more efficient representations that use vectors. The process of converting from an implimentation that uses indicies to one that uses vectors is known as vectorization. Once vectorized, the resulting implementation often yields to the user faster and more readable code than before.

In the following problems, we will ask you to practice reading mathematical expressions and deduce their vectorized equivalent along with their implementation in Python. You will use the PyTorch array object as the Python equivalent to a vector, and in later sections you will work with sets of vectors known as matrices.

In [7]:
def PYTORCH_dot(x, y):
    """
    Dot product of two tensors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.int64: scalar quantity.
    """

    return (x*y).sum()   # TODO

##### Test Example:

In [8]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)


X = numpy2tensor(X)
Y = numpy2tensor(Y)

print(PYTORCH_dot(X,Y))

tensor(7082791)


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_dot(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 7082791 </tt></td>
    </tr>
</table>

#### 2.2 Outer Product

In this task, you will implement the outer product function for torch tensors.

The outer product (also known as the tensor product) of vectors x and y is defined as

$$
x \otimes y =
\begin{bmatrix}
x_1 y_1 & x_1 y_2 & … & x_1 y_n\\
x_2 y_1 & x_2 y_2 & … & x_2 y_n\\
⋮ & ⋮ & ⋱ & ⋮ \\
x_m y_1 & x_m y_2 & … & x_m y_n
\end{bmatrix}
$$

**Your Task**: Implement the function `PYTORCH_outer`.


In [9]:
def PYTORCH_outer(x, y):
    """
    Compute the outer product of two vectors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """
    x = x.unsqueeze(1)
    y = y.unsqueeze(0)
    return x*y


##### Test Example:

In [10]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)


X = numpy2tensor(X)
Y = numpy2tensor(Y)

print(PYTORCH_outer(X,Y))

tensor([[  59092, -144096,  136512,  ...,  -53088,  -86268,   53404],
        [  82467, -201096,  190512,  ...,  -74088, -120393,   74529],
        [-122111,  297768, -282096,  ...,  109704,  178269, -110357],
        ...,
        [-144551,  352488, -333936,  ...,  129864,  211029, -130637],
        [-179707,  438216, -415152,  ...,  161448,  262353, -162409],
        [  88825, -216600,  205200,  ...,  -79800, -129675,   80275]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_outer(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;59092&nbsp;-144096&nbsp;&nbsp;136512&nbsp;...&nbsp;&nbsp;-53088&nbsp;&nbsp;-86268&nbsp;&nbsp;&nbsp;53404] <br>
            &nbsp;[&nbsp;&nbsp;82467&nbsp;-201096&nbsp;&nbsp;190512&nbsp;...&nbsp;&nbsp;-74088&nbsp;-120393&nbsp;&nbsp;&nbsp;74529] <br>
            &nbsp;[-122111&nbsp;&nbsp;297768&nbsp;-282096&nbsp;...&nbsp;&nbsp;109704&nbsp;&nbsp;178269&nbsp;-110357] <br>
            &nbsp;... <br>
            &nbsp;[-144551&nbsp;&nbsp;352488&nbsp;-333936&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;211029&nbsp;-130637] <br>
            &nbsp;[-179707&nbsp;&nbsp;438216&nbsp;-415152&nbsp;...&nbsp;&nbsp;161448&nbsp;&nbsp;262353&nbsp;-162409] <br>
            &nbsp;[&nbsp;&nbsp;88825&nbsp;-216600&nbsp;&nbsp;205200&nbsp;...&nbsp;&nbsp;-79800&nbsp;-129675&nbsp;&nbsp;&nbsp;80275]] <br>
        </tt></td>
    </tr>
</table>

#### 2.3 Hadamard Product

In this task, you will implement the Hadamard product function, `multiply`, for torch tensors.

The Hadamard product (also known as the Schur product or entrywise product) of vectors x and y is defined as

$$
x \circ y =
\begin{bmatrix}
x_{1} y_{1} & x_{2} y_{2} & … & x_{n} y_{n}
\end{bmatrix}
$$

**Your Task**: Implement the function `PYTORCH_multiply`.

In [11]:
def PYTORCH_multiply(x, y):
    """
    Multiply arguments element-wise.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.Tensor: 1-dimensional torch tensor.
    """

    return x * y   # TODO

In [12]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)


X = numpy2tensor(X)
Y = numpy2tensor(Y)

print(PYTORCH_multiply(X,Y))

tensor([  59092, -201096, -282096,  ...,  129864,  262353,   80275])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_multiply(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt>
            [&nbsp;&nbsp;59092&nbsp;-201096&nbsp;-282096&nbsp;...&nbsp;&nbsp;129864&nbsp;&nbsp;262353&nbsp;&nbsp;&nbsp;80275]
        </tt></td>
    </tr>
</table>

#### 2.4 Sum-Product
In this task, you will implement the sum-product function for torch tensors.

The sum-product of vectors x and y, each with n real component, is defined as

$$
f(x, y) =
{
\begin{bmatrix}
1\\
1\\
⋮\\
1
\end{bmatrix}^{\;T}
%
\begin{bmatrix}
x_1 y_1 & x_1 y_2 & … & x_1 y_n\\
x_2 y_1 & x_2 y_2 & … & x_2 y_n\\
⋮ & ⋮ & ⋱ & ⋮ \\
x_m y_1 & x_m y_2 & … & x_m y_n
\end{bmatrix}
%
\begin{bmatrix}
1\\
1\\
⋮\\
1
\end{bmatrix}
} =
\displaystyle\sum_{i=1}^{n} \displaystyle\sum_{j=1}^{n} x_i \cdot y_j
$$

**Your Task**: Implement the function `PYTORCH_sumproduct`.


In [13]:
def PYTORCH_sumproduct(x, y):
    """
    Sum over all the dimensions of the outer product of two vectors.

    Parameters:
    x (torch.Tensor): 1-dimensional torch tensor.
    y (torch.Tensor): 1-dimensional torch tensor.

    Returns:
    torch.int64: scalar quantity.
    """

    return  x.sum() * y.sum()   # TODO

##### Test Example:

In [14]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=3000)
Y = np.random.randint(-1000, 1000, size=3000)

X = numpy2tensor(X)
Y = numpy2tensor(Y)

print(PYTORCH_sumproduct(X,Y))

tensor(265421520)


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> TORCH_sumproduct(X,Y) </b></tt></td>
        <td style="text-align:left;"><tt> 265421520 </tt></td>
    </tr>
</table>

#### 2.5 ReLU

In this task, you will implement the ReLU activation function torch tensors.

The ReLU activation (also known as the rectifier or rectified linear unit) matrix Z resulting from applying the ReLU function to matrix X is defined such that for $X,Z \in M_{m \times n} (\mathbb{R})$,


**Your Task:** Implement the function `PYTORCH_ReLU`.

In [15]:
def PYTORCH_ReLU(x):
    """
    Applies the rectified linear unit function element-wise.

    Parameters:
    x (torch.Tensor): 2-dimensional torch tensor.

    Returns:
    torch.Tensor: 2-dimensional torch tensor.
    """

    return torch.clamp(x, min = 0)  # TODO

##### Test Example:

In [16]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))


X = numpy2tensor(X)

print(PYTORCH_ReLU(X))

tensor([[  0,   0, 653,  ..., 773, 961,   0],
        [  0, 456,   0,  ..., 168, 273,   0],
        [936, 475,   0,  ..., 408,   0,   0],
        ...,
        [  0, 396, 457,  ..., 646,   0,   0],
        [645, 943,   0,  ..., 863,   0, 790],
        [641,   0, 379,  ..., 347,   0,   0]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        </tt></td>
        <td style="text-align:left;"><tt><b> PYTORCH_ReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;653&nbsp;...&nbsp;773&nbsp;961&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;456&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;168&nbsp;273&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[936&nbsp;475&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;408&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[&nbsp;&nbsp;0&nbsp;396&nbsp;457&nbsp;...&nbsp;646&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0] <br>
&nbsp;[645&nbsp;943&nbsp;&nbsp;&nbsp;0&nbsp;...&nbsp;863&nbsp;&nbsp;&nbsp;0&nbsp;790] <br>
&nbsp;[641&nbsp;&nbsp;&nbsp;0&nbsp;379&nbsp;...&nbsp;347&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0]]
        </tt></td>
    </tr>
</table>

#### 2.6 Prime ReLU (derivative of ReLU)

In this task, you will implement the derivative of the ReLU activation function for torch tensors.

The derivative of the ReLU activation matrix Z resulting from applying the derivative of the ReLU function to matrix X is defined such that for $X,Z \in M_{m \times n} (\mathbb{R})$,



**Your Task:** Implement the function `PYTORCH_PrimeReLU`.

In [17]:
def PYTORCH_PrimeReLU(x):
    """
    Applies the derivative of the rectified linear unit function
    element-wise.

    Parameters:
    x (numpy.ndarray): 2-dimensional torch tensor.

    Returns:
    numpy.ndarray: 2-dimensional torch tensor.
    """
    # TODO

    return (x > 0).to(x.dtype)

##### Test Example:


In [18]:
np.random.seed(0)
X = np.random.randint(-1000, 1000, size=(3000,3000))

X = numpy2tensor(X)

print(PYTORCH_PrimeReLU(X))

tensor([[0, 0, 1,  ..., 1, 1, 0],
        [0, 1, 0,  ..., 1, 1, 0],
        [1, 1, 0,  ..., 1, 0, 0],
        ...,
        [0, 1, 1,  ..., 1, 0, 0],
        [1, 1, 0,  ..., 1, 0, 1],
        [1, 0, 1,  ..., 1, 0, 0]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_PrimeReLU(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[0&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[0&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;1&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;... <br>
&nbsp;[0&nbsp;1&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0] <br>
&nbsp;[1&nbsp;1&nbsp;0&nbsp;...&nbsp;1&nbsp;0&nbsp;1] <br>
&nbsp;[1&nbsp;0&nbsp;1&nbsp;...&nbsp;1&nbsp;0&nbsp;0]]
        </tt></td>
    </tr>
</table>

### **3. Tensor Manipulation**

PyTorch offers a wide range of tensor manipulation tasks that empower users to efficiently process and transform data within neural network workflows.
These tasks include :
1.  Flatten
2.  Unsqueeze
3.  Squeeze
4.  Reshape
5.  Transpose
6.  Permute
7.  Concatenation
8.  Stack
9.  Padding

#### 3.1 Flatten

In this task, you will implement the flatten function for torch tensors.




**Your Task:** Implement the function `PYTORCH_flatten`.

In [19]:
def PYTORCH_flatten(input_tensor):
    """
    Reshapes a tensor into a 1-dimensional array while maintaining the order of elements.

    Parameters:
    x (torch.Tensor): 3-dimensional torch tensor.

    Returns:
    torch.Tensor: 1-dimensional torch tensor.
    """
    m = torch.nn.Flatten()
    return torch.flatten(input_tensor)
    # return NotImplemented #TODO

##### Test Example:

In [20]:
np.random.seed(0)
X = np.random.randint(-10, 10, size=(100,100,100))

X = numpy2tensor(X)

print(PYTORCH_flatten(X))

tensor([  2,   5, -10,  ...,   1,   3,  -3])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_flatten(X) </b></tt></td>
        <td style="text-align:left;"><tt>
            [  2,   5, -10,  ...,   1,   3,  -3]
        </tt></td>
    </tr>
</table>

#### 3.2 Unsqueeze

In this task, you will implement the unsqueeze function for torch tensors along given dimension.




**Your Task:** Implement the function `PYTORCH_unsqueeze`.

In [21]:
def PYTORCH_unsqueeze(X,dim):
    """
    Adds a new dimension to a tensor at the specified position 'dim'.

    Parameters:
    x (torch.Tensor): 2-dimensional torch tensor.

    dim (int): scalar.

    Returns:
    torch.Tensor: 3-dimensional torch tensor.
    """

    return X.unsqueeze(dim) #TODO

##### Test Example:

In [22]:
np.random.seed(0)
X = np.random.randint(0, 5, size=(100,100))

X = numpy2tensor(X)

print(PYTORCH_unsqueeze(X,0))
print("\n")

print("Shape before unsqueeze: ",X.shape)
print("Shape after unsqueeze: ",PYTORCH_unsqueeze(X,0).shape)

tensor([[[4, 0, 3,  ..., 2, 2, 3],
         [2, 3, 2,  ..., 2, 3, 3],
         [1, 3, 4,  ..., 0, 2, 4],
         ...,
         [2, 0, 1,  ..., 4, 4, 3],
         [2, 4, 3,  ..., 3, 0, 0],
         [2, 3, 4,  ..., 4, 3, 1]]])


Shape before unsqueeze:  torch.Size([100, 100])
Shape after unsqueeze:  torch.Size([1, 100, 100])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_unsqueeze(X) </b></tt></td>
        <td style="text-align:left;"><tt>
        [[[4&nbsp;0&nbsp;3&nbsp;...&nbsp;2&nbsp;2&nbsp;3] <br>
&nbsp; [2&nbsp;3&nbsp;2&nbsp;...&nbsp;2&nbsp;3&nbsp;3] <br>
&nbsp; [1&nbsp;3&nbsp;4&nbsp;...&nbsp;0&nbsp;2&nbsp;4] <br>
&nbsp; ..., <br>
&nbsp; [2&nbsp;0&nbsp;1&nbsp;...&nbsp;4&nbsp;4&nbsp;3] <br>
&nbsp; [2&nbsp;4&nbsp;3&nbsp;...&nbsp;3&nbsp;0&nbsp;0] <br>
&nbsp; [2&nbsp;3&nbsp;4&nbsp;...&nbsp;4&nbsp;3&nbsp;1]]]<br>
<br>
Shape before unsqueeze:  torch.Size([100, 100]) <br>
Shape after unsqueeze:  torch.Size([1, 100, 100])
        </tt></td>
    </tr>
</table>

#### 3.3 Squeeze

In this task, you will implement the squeeze function for torch tensors along axis with dimension 1 (axis = 0).




**Your Task:** Implement the function `PYTORCH_squeeze`.

In [23]:
def PYTORCH_squeeze(X,dim):
    """
    Removes dimension to a tensor at the specified position 'dim'.

    Parameters:
    x (torch.Tensor): 2-dimensional torch tensor.

    dim (integer): scalar.

    Returns:
    torch.Tensor: 1-dimensional torch tensor.
    """

    return X.squeeze(dim) #TODO

#### Test Example:

In [24]:
np.random.seed(0)
X = np.random.randint(0, 10, size=(1,5))

X = numpy2tensor(X)



print(PYTORCH_squeeze(X,0))

print("Shape of tensor before squeeze: ",X.shape)
print("Shape of tensor after squeeze: ",PYTORCH_squeeze(X,0).shape )

tensor([5, 0, 3, 3, 7])
Shape of tensor before squeeze:  torch.Size([1, 5])
Shape of tensor after squeeze:  torch.Size([5])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_squeeze(X) </b></tt></td>
        <td style="text-align:left;"><tt>
        [5&nbsp;0&nbsp;3&nbsp;3&nbsp;7&nbsp;] <br>
Shape of tensor before squeeze:  torch.Size([1, 5]) <br>
Shape of tensor after squeeze:  torch.Size([5])
        </tt></td>
    </tr>
</table>

#### 3.4 Reshape

In this task, you will implement the reshape function for torch tensors.




**Your Task:** Implement the function `PYTORCH_reshape`.

In [28]:
def PYTORCH_reshape(X,new_shape):
    """
    Reorganizes the tensor's elements to match a specified shape while maintaining the same number of elements.

    Parameters:
    x (torch.Tensor): 3-dimensional torch tensor.

    new_shape (tuple): tuple with 3 elements which represents the new shape of the tensor.

    Returns:
    torch.Tensor: torch tensor of dimension 'new_shape'.
    """
    return X.reshape(new_shape) #TODO

#### Test Example:

In [29]:
np.random.seed(0)
X = np.random.randint(0, 10, size=(3,10))

X = numpy2tensor(X)



print(PYTORCH_reshape(X,(2,3,5)))

tensor([[[5, 0, 3, 3, 7],
         [9, 3, 5, 2, 4],
         [7, 6, 8, 8, 1]],

        [[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0]]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_reshape(X,new_shape) </b></tt></td>
        <td style="text-align:left;"><tt>
             [[[5,&nbsp;0,&nbsp;3,&nbsp;3,&nbsp;7&nbsp;], <br>
        &nbsp; [9,&nbsp;3,&nbsp;5,&nbsp;2,&nbsp;4&nbsp;], <br>
        &nbsp; [7,&nbsp;6,&nbsp;8,&nbsp;8,&nbsp;1&nbsp;]], <br>
        <br>
        &nbsp;[[6,&nbsp;7,&nbsp;7,&nbsp;8,&nbsp;1&nbsp;], <br>
        &nbsp; [5,&nbsp;9,&nbsp;8,&nbsp;9,&nbsp;4&nbsp;], <br>
        &nbsp; [3,&nbsp;0,&nbsp;3,&nbsp;5,&nbsp;0&nbsp;]]]
        
</table>

#### 3.5 Transpose

In this task, you will implement the transpose function for torch tensors.




**Your Task:** Implement the function `PYTORCH_transpose`.

In [30]:
def PYTORCH_transpose(X,dim0,dim1):
    """
    Reorganizes the tensor's elements and shape effectively by swapping along given direction.

    Parameters:
    x (torch.Tensor): 3-dimensional torch tensor.

    dim0 (int): the first dimension to be transposed.

    dim1 (int): the second dimension to be transposed.

    Returns:
    torch.Tensor: torch tensor of transposed version input.
    """
    return X.transpose(dim0, dim1) #TODO

#### Test Example:

In [31]:
np.random.seed(0)
X = np.random.randint(0, 10, size=(2,3,4))

X = numpy2tensor(X)


print(PYTORCH_transpose(X,1,2))

tensor([[[5, 7, 2],
         [0, 9, 4],
         [3, 3, 7],
         [3, 5, 6]],

        [[8, 7, 5],
         [8, 7, 9],
         [1, 8, 8],
         [6, 1, 9]]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_transpose(X,dim0,dim1) </b></tt></td>
        <td style="text-align:left;"><tt>
             [[[5,&nbsp;7,&nbsp;2,], <br>
        &nbsp; [0,&nbsp;9,&nbsp;4,], <br>
        &nbsp; [3,&nbsp;3,&nbsp;7,], <br>
        &nbsp; [3,&nbsp;5,&nbsp;6,]], <br>
        <br>
        &nbsp;[[8,&nbsp;7,&nbsp;5,], <br>
        &nbsp; [8,&nbsp;7,&nbsp;9,], <br>
        &nbsp; [1,&nbsp;8,&nbsp;8,], <br>
        &nbsp; [6,&nbsp;1,&nbsp;9,]]] <br>
        
</table>

#### 3.6 Permute

In this task, you will implement the permute function for torch tensors.




**Your Task:** Implement the function `PYTORCH_permute`.

In [32]:
def PYTORCH_permute(X,dims):
    """
    Reorganizes the the dimensions of a tensor according to a specified permutation tuple while maintaining the data's order.

    Parameters:
    x (torch.Tensor): 3-dimensional torch tensor.

    dims (tuple): tuple of integers that represents axis to be permuted

    Returns:
    torch.Tensor: torch tensor of permuted version input.
    """
    return X.permute(dims) #TODO

#### Test Example:

In [33]:
np.random.seed(0)
X = np.random.randint(0, 10, size=(2,3,4))

X = numpy2tensor(X)


print(PYTORCH_permute(X,(2,0,1)))

tensor([[[5, 7, 2],
         [8, 7, 5]],

        [[0, 9, 4],
         [8, 7, 9]],

        [[3, 3, 7],
         [1, 8, 8]],

        [[3, 5, 6],
         [6, 1, 9]]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_permute(X,dims) </b></tt></td>
        <td style="text-align:left;"><tt>
             [[[5,&nbsp;7,&nbsp;2,], <br>
        &nbsp; [8,&nbsp;7,&nbsp;5,]], <br>
        <br>
        &nbsp;[[0,&nbsp;9,&nbsp;4,], <br>
        &nbsp; [8,&nbsp;7,&nbsp;9,]], <br>
        <br>
        &nbsp;[[3,&nbsp;3,&nbsp;7,], <br>
        &nbsp; [1,&nbsp;8,&nbsp;8,]], <br>
        <br>
        &nbsp;[[3,&nbsp;5,&nbsp;6,], <br>
        &nbsp; [6,&nbsp;1,&nbsp;9,]]] <br>
        
</table>

#### 3.7 Concatenate

In this task, you will implement the Concatenate function for torch tensors.




**Your Task:** Implement the function `PYTORCH_concatenate`.

In [36]:
def PYTORCH_concatenate(tensors,dim):
    """
    Reorganizes the the dimensions of a tensor according to a specified permutation tuple while maintaining the data's order.

    Parameters:
    tensors (tuple): tuple of Tensors with same shape except in concatenate dimension.

    dim (int): concatenate dimension

    Returns:
    torch.Tensor: concatenated tensor.
    """
    return torch.cat(tensors,dim)

#### Test Example:

In [37]:
np.random.seed(0)
X = np.random.randint(0, 10, size=(2,3,4))
Y = np.random.randint(0, 3, size=(2,3,3))
X = numpy2tensor(X)
Y = numpy2tensor(Y)


print(PYTORCH_concatenate((X,Y),2))

tensor([[[5, 0, 3, 3, 0, 0, 1],
         [7, 9, 3, 5, 2, 0, 2],
         [2, 4, 7, 6, 0, 1, 1]],

        [[8, 8, 1, 6, 2, 0, 1],
         [7, 7, 8, 1, 1, 1, 0],
         [5, 9, 8, 9, 2, 0, 2]]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_concatenate(tensors,dim) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[[5,&nbsp;0,&nbsp;3,&nbsp;3,&nbsp;0,&nbsp;0,&nbsp;1], <br>
            &nbsp; [7,&nbsp;9,&nbsp;3,&nbsp;5,&nbsp;2,&nbsp;0,&nbsp;2], <br>
            &nbsp; [2,&nbsp;4,&nbsp;7,&nbsp;6,&nbsp;0,&nbsp;1,&nbsp;1]],<br>
            <br>
            &nbsp;[[8,&nbsp;8,&nbsp;1,&nbsp;6,&nbsp;2,&nbsp;0,&nbsp;1], <br>
            &nbsp; [7,&nbsp;7,&nbsp;8,&nbsp;1,&nbsp;1,&nbsp;1,&nbsp;0], <br>
            &nbsp; [5,&nbsp;9,&nbsp;8,&nbsp;9,&nbsp;2,&nbsp;0,&nbsp;2]]],<br>
       
        
</table>

#### 3.8 Stack

In this task, you will implement the stack function for torch tensors.




**Your Task:** Implement the function `PYTORCH_stack`.

In [38]:
def PYTORCH_stack(tensors,dim):

    """
    In contrast to Concatenation, which merges two tensors along an existing dimension,
    Stack creates a new dimension to combine tensors.

    Parameters:
    tensors (tuple):  tuple of tensors to be stacked
    dim (int): dimension to insert.

    Returns:
    torch.Tensor: stacked tensor.
    """

    return torch.stack(tensors,dim) #TODO


#### Test Example:

In [39]:
np.random.seed(0)
X = np.random.randint(0, 10, size=(2,3))
Y = np.random.randint(0, 3, size=(2,3))
X = numpy2tensor(X)
Y = numpy2tensor(Y)


print(PYTORCH_stack((X,Y),1))

tensor([[[5, 0, 3],
         [1, 2, 0]],

        [[3, 7, 9],
         [2, 0, 0]]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_stack(tensors,dims) </b></tt></td>
        <td style="text-align:left;"><tt>
            [[[5,&nbsp;0,&nbsp;3,], <br>
        &nbsp; [1,&nbsp;2,&nbsp;0,]], <br>
        <br>
        &nbsp;[[3,&nbsp;7,&nbsp;9,], <br>
        &nbsp; [2,&nbsp;0,&nbsp;0,]]], <br>
        <br>
        
</table>

#### 3.9 Padding

In this task, you will implement the padding  function for torch tensors.




**Your Task:** Implement the function `PYTORCH_padding`.

In [44]:
def PYTORCH_padding(X,pad_widths):

    """
    This involves adding extra elements (usually zeros) around the edges of a tensor.
    We will encounter this during convolutional operations to control the spatial dimensions of the output.

    Parameters:
    X (torch.Tensor): input tensor which is to be padded.
    pad_widths (tuple): even number of elements in tuple that represents padding widths in the order columns,rows and channels.

    Returns:
    torch.Tensor: stacked tensor.
    """

    return torch.nn.functional.pad(X,pad_widths) #TODO

In [45]:
np.random.seed(0)
X = np.random.randint(1, 10, size=(2,2,2))

X = numpy2tensor(X)


print(PYTORCH_padding(X,(2,2,1,1,0,0)))

tensor([[[0, 0, 0, 0, 0, 0],
         [0, 0, 6, 1, 0, 0],
         [0, 0, 4, 4, 0, 0],
         [0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0],
         [0, 0, 8, 4, 0, 0],
         [0, 0, 6, 3, 0, 0],
         [0, 0, 0, 0, 0, 0]]])


**Expected Output**:
<table style = "align:40%">
    <tr>
        <td style="text-align:left;"><tt><b> PYTORCH_padding(X,pad_widths) </b></tt></td>
        <td style="text-align:left;"><tt>
     [[[0,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;0],<br>
&nbsp; [0,&nbsp;0,&nbsp;6,&nbsp;1,&nbsp;0,&nbsp;0], <br>
&nbsp; [0,&nbsp;0,&nbsp;4,&nbsp;4,&nbsp;0,&nbsp;0], <br>
&nbsp; [0,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;0]] <br>
<br>
&nbsp;[[0,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;0], <br>
&nbsp; [0,&nbsp;0,&nbsp;8,&nbsp;4,&nbsp;0,&nbsp;0], <br>
&nbsp; [0,&nbsp;0,&nbsp;6,&nbsp;3,&nbsp;0,&nbsp;0], <br>
&nbsp; [0,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;0,&nbsp;0]]]
        </tt></td>
    </tr>
</table>

### **4. Build a Neural Network**

Now we go through the basic concepts and functionalities of PyTorch to build a neural network. By the end of this notebook, you'll understand some basics on dataloaders/datasets, build simple neural networks, and train a model. You will also get context on how PyTorch runs computations on the CPU and GPU, and what CUDA is.


#### 4.1. Setting Up the Environment

First, we need to install PyTorch. You can install it using pip. Run the following command in your terminal or in a code cell:

In [46]:
!pip install torch torchvision

#### 4.2. Importing PyTorch

Now, let's import necessary PyTorch libraries.

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms

#### 4.2.1 CUDA

When you train a neural network, PyTorch needs to know where to run the computations — either:

1. On your CPU (default if no GPU is available), or

2. On your GPU (which is much faster for deep learning, if available).

Below is a standard way to check this in PyTorch. What this line does:

- Checks if a CUDA-compatible GPU is available (i.e., an NVIDIA GPU). If it is, it sets device to "cuda", so your model/data will run on the GPU. This means you can achieve much faster training for large datasets (such as the ones you'll see in homeworks)
- If you see device = "cpu", it means you're not connected to any GPUs - make sure they are selected in Google Collab / Kaggle / Active on your machine. If you use your CPU for training, it will be much slower for large models or datasets.




In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

#### 4.3. Building a Neural Network

Now, let's build a simple neural network using PyTorch. We'll create a basic feedforward network to classify handwritten digits from the MNIST dataset. Once we have built our network, we must move it to our computational device so that PyTorch knows what resource to use for training.

In [4]:
class SimpleNN(nn.Module):
  def __init__(self):
    super(SimpleNN, self).__init__()
    self.fc1=nn.Linear(28*28, 128)
    self.fc2=nn.Linear(128,64)
    self.fc3=nn.Linear(64,10)

  def forward(self, x):
    x=x.view(-1, 28*28)
    x=F.relu(self.fc1(x))
    x=F.relu(self.fc2(x))
    x=self.fc3(x)
    return x

net=SimpleNN().to(device)

#### 4.4. Loading the Dataset

In [5]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

trainset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle=True)

testset = torchvision.datasets.MNIST(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=32, shuffle=False)

100%|██████████| 9.91M/9.91M [00:00<00:00, 11.5MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 344kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 3.18MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 7.65MB/s]


#### 4.5. Defining the Loss Function and Optimizer

In [6]:
criterion=nn.CrossEntropyLoss()
optimizer=optim.SGD(net.parameters(), lr=0.01, momentum=0.9)

#### 4.6. Training the network

In [7]:
for epoch in range(5): #Loop over the dataset multiple time
  running_loss=0.0
  for i, data in enumerate(trainloader, 0):
    inputs, lables=data
    inputs, labels=inputs.to(device), lables.to(device)
    optimizer.zero_grad()
    outputs=net(inputs)
    loss=criterion(outputs, labels)
    loss.backward()
    optimizer.step()

    running_loss +=loss.item()
    if i%100 ==99: #print every 100 miini_batches
      print(f'[Epoch {epoch+1}, Batch {i+1}] loss: {running_loss/100:.3f}')
      running_loss=0.0
print('Finished Training')

[Epoch 1, Batch 100] loss: 1.405
[Epoch 1, Batch 200] loss: 0.544
[Epoch 1, Batch 300] loss: 0.467
[Epoch 1, Batch 400] loss: 0.364
[Epoch 1, Batch 500] loss: 0.371
[Epoch 1, Batch 600] loss: 0.337
[Epoch 1, Batch 700] loss: 0.327
[Epoch 1, Batch 800] loss: 0.276
[Epoch 1, Batch 900] loss: 0.311
[Epoch 1, Batch 1000] loss: 0.267
[Epoch 1, Batch 1100] loss: 0.228
[Epoch 1, Batch 1200] loss: 0.236
[Epoch 1, Batch 1300] loss: 0.228
[Epoch 1, Batch 1400] loss: 0.221
[Epoch 1, Batch 1500] loss: 0.207
[Epoch 1, Batch 1600] loss: 0.216
[Epoch 1, Batch 1700] loss: 0.191
[Epoch 1, Batch 1800] loss: 0.194
[Epoch 2, Batch 100] loss: 0.184
[Epoch 2, Batch 200] loss: 0.188
[Epoch 2, Batch 300] loss: 0.146
[Epoch 2, Batch 400] loss: 0.167
[Epoch 2, Batch 500] loss: 0.182
[Epoch 2, Batch 600] loss: 0.157
[Epoch 2, Batch 700] loss: 0.143
[Epoch 2, Batch 800] loss: 0.161
[Epoch 2, Batch 900] loss: 0.181
[Epoch 2, Batch 1000] loss: 0.159
[Epoch 2, Batch 1100] loss: 0.135
[Epoch 2, Batch 1200] loss: 0.17

In [8]:
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        images, labels = images.to(device), labels.to(device)
        outputs = net(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy of the network on the 10000 test images: {100 * correct / total:.2f}%')

Accuracy of the network on the 10000 test images: 95.21%


#### 4.6. Conclusion

Bravo! Just now, using PyTorch, you constructed and trained a basic neural network. We discussed:


Build and work with tensors

Constructing a neural network

Testing and educating the network

Try changing the training parameters and network architecture to observe how it affects performance. Cheers to learning!